theme: jekyll-theme-midnight
title: "ka2is hacking journey"
description: "let's hack"

# minima theme import below
show_excerpts: true # set to false to remove excerpts on the homepage
excerpt_separator: "<!--end-excerpt-->"
date_format: "%-d b %Y"
