theme: jekyll-theme-midnight
title: "kai2s hacking journey"
description: "let's break something"

# my variables inspired by minima theme below
show_excerpts: true # set to false to remove excerpts on the homepage
excerpt_separator: "<!--end-excerpt-->"
date_format: "%-d %B %Y"
